package com.shinowit.dao.mapper;

import com.shinowit.entity.Chart;
import com.shinowit.entity.ChartCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int countByExample(ChartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int deleteByExample(ChartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int deleteByPrimaryKey(Integer chartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int insert(Chart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int insertSelective(Chart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    List<Chart> selectByExample(ChartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    Chart selectByPrimaryKey(Integer chartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") Chart record, @Param("example") ChartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int updateByExample(@Param("record") Chart record, @Param("example") ChartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int updateByPrimaryKeySelective(Chart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Dec 29 21:11:42 CST 2014
     */
    int updateByPrimaryKey(Chart record);

    List<Chart> selectPage(ChartCriteria example);

    Integer selectMaxPrimaryKeyValue();
}