package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Chart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.chartid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private Integer chartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.picth
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private String picth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.merchandisename
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private String merchandisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.price
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.num
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.smallsum
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private BigDecimal smallsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.merberid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private Integer merberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.chartid
     *
     * @return the value of chart.chartid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public Integer getChartid() {
        return chartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.chartid
     *
     * @param chartid the value for chart.chartid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setChartid(Integer chartid) {
        this.chartid = chartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.picth
     *
     * @return the value of chart.picth
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public String getPicth() {
        return picth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.picth
     *
     * @param picth the value for chart.picth
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setPicth(String picth) {
        this.picth = picth == null ? null : picth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.merchandisename
     *
     * @return the value of chart.merchandisename
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public String getMerchandisename() {
        return merchandisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.merchandisename
     *
     * @param merchandisename the value for chart.merchandisename
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setMerchandisename(String merchandisename) {
        this.merchandisename = merchandisename == null ? null : merchandisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.price
     *
     * @return the value of chart.price
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.price
     *
     * @param price the value for chart.price
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.num
     *
     * @return the value of chart.num
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.num
     *
     * @param num the value for chart.num
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.smallsum
     *
     * @return the value of chart.smallsum
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public BigDecimal getSmallsum() {
        return smallsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.smallsum
     *
     * @param smallsum the value for chart.smallsum
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setSmallsum(BigDecimal smallsum) {
        this.smallsum = smallsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.merberid
     *
     * @return the value of chart.merberid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public Integer getMerberid() {
        return merberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.merberid
     *
     * @param merberid the value for chart.merberid
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    public void setMerberid(Integer merberid) {
        this.merberid = merberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chart other = (Chart) that;
        return (this.getChartid() == null ? other.getChartid() == null : this.getChartid().equals(other.getChartid()))
            && (this.getPicth() == null ? other.getPicth() == null : this.getPicth().equals(other.getPicth()))
            && (this.getMerchandisename() == null ? other.getMerchandisename() == null : this.getMerchandisename().equals(other.getMerchandisename()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getSmallsum() == null ? other.getSmallsum() == null : this.getSmallsum().equals(other.getSmallsum()))
            && (this.getMerberid() == null ? other.getMerberid() == null : this.getMerberid().equals(other.getMerberid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Wed Dec 31 14:43:42 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChartid() == null) ? 0 : getChartid().hashCode());
        result = prime * result + ((getPicth() == null) ? 0 : getPicth().hashCode());
        result = prime * result + ((getMerchandisename() == null) ? 0 : getMerchandisename().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getSmallsum() == null) ? 0 : getSmallsum().hashCode());
        result = prime * result + ((getMerberid() == null) ? 0 : getMerberid().hashCode());
        return result;
    }
}