package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Chart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.chartid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private Integer chartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.picth
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private String totalmoney;

    private String picth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.merchandisename
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private String merchandisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.price
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.num
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.smallsum
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private BigDecimal smallsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.merberid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private Integer merberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.chartid
     *
     * @return the value of chart.chartid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public Integer getChartid() {
        return chartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.chartid
     *
     * @param chartid the value for chart.chartid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setChartid(Integer chartid) {
        this.chartid = chartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.picth
     *
     * @return the value of chart.picth
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public String getPicth() {
        return picth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.picth
     *
     * @param picth the value for chart.picth
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setPicth(String picth) {
        this.picth = picth == null ? null : picth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.merchandisename
     *
     * @return the value of chart.merchandisename
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public String getMerchandisename() {
        return merchandisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.merchandisename
     *
     * @param merchandisename the value for chart.merchandisename
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setMerchandisename(String merchandisename) {
        this.merchandisename = merchandisename == null ? null : merchandisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.price
     *
     * @return the value of chart.price
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.price
     *
     * @param price the value for chart.price
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.num
     *
     * @return the value of chart.num
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.num
     *
     * @param num the value for chart.num
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.smallsum
     *
     * @return the value of chart.smallsum
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public BigDecimal getSmallsum() {
        return smallsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.smallsum
     *
     * @param smallsum the value for chart.smallsum
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setSmallsum(BigDecimal smallsum) {
        this.smallsum = smallsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.merberid
     *
     * @return the value of chart.merberid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public Integer getMerberid() {
        return merberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.merberid
     *
     * @param merberid the value for chart.merberid
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setMerberid(Integer merberid) {
        this.merberid = merberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public String getTotalmoney() {
        return totalmoney;
    }

    public void setTotalmoney(String totalmoney) {
        this.totalmoney = totalmoney;
    }
}