package com.shinowit.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ChartCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    private int pageIndex;

    private int pageSize;

    private String customCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public ChartCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setPageIndex(int pageIndex) {
        this.pageIndex=pageIndex;
    }

    public int getPageIndex() {
        return this.pageIndex;
    }

    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    public int getPageSize() {
        return this.pageSize;
    }

    public void setCustomCriteria(String customCriteria) {
        this.customCriteria=customCriteria;
    }

    public String getCustomCriteria() {
        return this.customCriteria;
    }

    public int getSkipRecordCount() {
        int count=(this.pageIndex-1)*this.pageSize;
        if (count<0){
             count=0;
        }
        return count;
    }

    public int getEndRecordCount() {
        return this.pageIndex*this.pageSize;
    }

    public ChartCriteria(int pageSize, int pageIndex) {
        this();
        this.pageSize=pageSize;
        this.pageIndex=pageIndex;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChartidIsNull() {
            addCriterion("chartid is null");
            return (Criteria) this;
        }

        public Criteria andChartidIsNotNull() {
            addCriterion("chartid is not null");
            return (Criteria) this;
        }

        public Criteria andChartidEqualTo(Integer value) {
            addCriterion("chartid =", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidNotEqualTo(Integer value) {
            addCriterion("chartid <>", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidGreaterThan(Integer value) {
            addCriterion("chartid >", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidGreaterThanOrEqualTo(Integer value) {
            addCriterion("chartid >=", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidLessThan(Integer value) {
            addCriterion("chartid <", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidLessThanOrEqualTo(Integer value) {
            addCriterion("chartid <=", value, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidIn(List<Integer> values) {
            addCriterion("chartid in", values, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidNotIn(List<Integer> values) {
            addCriterion("chartid not in", values, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidBetween(Integer value1, Integer value2) {
            addCriterion("chartid between", value1, value2, "chartid");
            return (Criteria) this;
        }

        public Criteria andChartidNotBetween(Integer value1, Integer value2) {
            addCriterion("chartid not between", value1, value2, "chartid");
            return (Criteria) this;
        }

        public Criteria andPicthIsNull() {
            addCriterion("picth is null");
            return (Criteria) this;
        }

        public Criteria andPicthIsNotNull() {
            addCriterion("picth is not null");
            return (Criteria) this;
        }

        public Criteria andPicthEqualTo(String value) {
            addCriterion("picth =", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthNotEqualTo(String value) {
            addCriterion("picth <>", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthGreaterThan(String value) {
            addCriterion("picth >", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthGreaterThanOrEqualTo(String value) {
            addCriterion("picth >=", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthLessThan(String value) {
            addCriterion("picth <", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthLessThanOrEqualTo(String value) {
            addCriterion("picth <=", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthLike(String value) {
            addCriterion("picth like", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthNotLike(String value) {
            addCriterion("picth not like", value, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthIn(List<String> values) {
            addCriterion("picth in", values, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthNotIn(List<String> values) {
            addCriterion("picth not in", values, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthBetween(String value1, String value2) {
            addCriterion("picth between", value1, value2, "picth");
            return (Criteria) this;
        }

        public Criteria andPicthNotBetween(String value1, String value2) {
            addCriterion("picth not between", value1, value2, "picth");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameIsNull() {
            addCriterion("merchandisename is null");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameIsNotNull() {
            addCriterion("merchandisename is not null");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameEqualTo(String value) {
            addCriterion("merchandisename =", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameNotEqualTo(String value) {
            addCriterion("merchandisename <>", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameGreaterThan(String value) {
            addCriterion("merchandisename >", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameGreaterThanOrEqualTo(String value) {
            addCriterion("merchandisename >=", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameLessThan(String value) {
            addCriterion("merchandisename <", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameLessThanOrEqualTo(String value) {
            addCriterion("merchandisename <=", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameLike(String value) {
            addCriterion("merchandisename like", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameNotLike(String value) {
            addCriterion("merchandisename not like", value, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameIn(List<String> values) {
            addCriterion("merchandisename in", values, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameNotIn(List<String> values) {
            addCriterion("merchandisename not in", values, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameBetween(String value1, String value2) {
            addCriterion("merchandisename between", value1, value2, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameNotBetween(String value1, String value2) {
            addCriterion("merchandisename not between", value1, value2, "merchandisename");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andSmallsumIsNull() {
            addCriterion("smallsum is null");
            return (Criteria) this;
        }

        public Criteria andSmallsumIsNotNull() {
            addCriterion("smallsum is not null");
            return (Criteria) this;
        }

        public Criteria andSmallsumEqualTo(BigDecimal value) {
            addCriterion("smallsum =", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumNotEqualTo(BigDecimal value) {
            addCriterion("smallsum <>", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumGreaterThan(BigDecimal value) {
            addCriterion("smallsum >", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("smallsum >=", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumLessThan(BigDecimal value) {
            addCriterion("smallsum <", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("smallsum <=", value, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumIn(List<BigDecimal> values) {
            addCriterion("smallsum in", values, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumNotIn(List<BigDecimal> values) {
            addCriterion("smallsum not in", values, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("smallsum between", value1, value2, "smallsum");
            return (Criteria) this;
        }

        public Criteria andSmallsumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("smallsum not between", value1, value2, "smallsum");
            return (Criteria) this;
        }

        public Criteria andMerberidIsNull() {
            addCriterion("merberid is null");
            return (Criteria) this;
        }

        public Criteria andMerberidIsNotNull() {
            addCriterion("merberid is not null");
            return (Criteria) this;
        }

        public Criteria andMerberidEqualTo(Integer value) {
            addCriterion("merberid =", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidNotEqualTo(Integer value) {
            addCriterion("merberid <>", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidGreaterThan(Integer value) {
            addCriterion("merberid >", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidGreaterThanOrEqualTo(Integer value) {
            addCriterion("merberid >=", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidLessThan(Integer value) {
            addCriterion("merberid <", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidLessThanOrEqualTo(Integer value) {
            addCriterion("merberid <=", value, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidIn(List<Integer> values) {
            addCriterion("merberid in", values, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidNotIn(List<Integer> values) {
            addCriterion("merberid not in", values, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidBetween(Integer value1, Integer value2) {
            addCriterion("merberid between", value1, value2, "merberid");
            return (Criteria) this;
        }

        public Criteria andMerberidNotBetween(Integer value1, Integer value2) {
            addCriterion("merberid not between", value1, value2, "merberid");
            return (Criteria) this;
        }

        public Criteria andPicthLikeInsensitive(String value) {
            addCriterion("upper(picth) like", value.toUpperCase(), "picth");
            return (Criteria) this;
        }

        public Criteria andMerchandisenameLikeInsensitive(String value) {
            addCriterion("upper(merchandisename) like", value.toUpperCase(), "merchandisename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chart
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 05 19:10:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chart
     *
     * @mbggenerated Mon Jan 05 19:10:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}